### ISSUE TITLE
No one click memory timing

### ISSUE THREAD

**Issue by BoriZka67** [vvaske/PolarisBiosEditor#3]
[bios_rx580_8gb_original_RedDragon_SN_DG1909024865.txt](https://github.com/vvaske/PolarisBiosEditor/files/4249251/bios_rx580_8gb_original_RedDragon_SN_DG1909024865.txt)
txt => rom

https://github.com/IndeedMiners/PBE-Polaris-Bios-Editor-1.7.2/issues/2

**Comment by vvaske** [comment]
Sorry for late response, fixed error, also i call it "**samsung4**" memory...
