### ISSUE TITLE
Editor shows weird GPU voltages

### ISSUE THREAD

**Issue by twizzter** [vvaske/PolarisBiosEditor#5]
Hi,
I used GPUZ to dump rom of MSI RX580, after opening it in PBE 1.7.3 found weird core voltages fields:

MHz    mV
300 750
600 65282
918 65283
1167 65284
etc

Driver settings reverted to stock.
Could it be caused by invalid dump or PBE error?
[Ellesmere.txt](https://github.com/vvaske/PolarisBiosEditor/files/4855822/Ellesmere.txt)

**Comment by vvaske** [comment]
That's normal voltages, mean factory

**Comment by swapnanil1** [comment]
@vvaske  so can we change 652XX them directly?
